### PR TITLE
Unexplored areas locator

### PR DESCRIPTION
**Pull request by proydoha**
~Draft, work in progress~

More or less done

### CODE REVIEW

**Comment by proydoha** [comment]
Okay, I'm marking it as "Ready". In my head its still experimental and maybe we should title its menu as such but overall I think it is more or less working.

**Comment by proydoha** [comment]
@Alando1-doom 
And it needs two sounds at the end of `SNDINFO.pathfinder`:
- pathfinder/unexplored
- pathfinder/noninteracted

**Comment by Alando1-doom** [comment]
Looks great! I will proceed to merge. I could include in the voiceover "Exploration - Experimental Feature" if you'd like. In regard to the 2 other sounds you mentioned, "unexplored" and "non-interacted," I noticed you have them in the script as "BEEP1" and "CRICKET". Did you want me to voice "unexplored" and "non-interacted" or are the current sounds sufficient enough?

**Review by Alando1-doom — COMMENTED** [review]
Looking great! Will merge pull request.

**Comment by proydoha** [comment]
> I noticed you have them in the script as "BEEP1" and "CRICKET". Did you want me to voice "unexplored" and "non-interacted" or are the current sounds sufficient enough?

That's just to put something to play to verify that my code works. I would put "unexplored" and "non-interacted".
Try it yourself. Maybe you'll come up with better description.

**Pull request merged**
